# CircleCI configuration for GemGuard security scanning
# Copy this content to .circleci/config.yml in your repository

version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  security-scan:
    docker:
      - image: cimg/ruby:3.3
    parameters:
      ruby-version:
        type: string
        default: "3.3"
    steps:
      - checkout
      
      - ruby/install-deps:
          bundler-version: "2.4.0"
          
      - run:
          name: Install GemGuard
          command: gem install gem_guard
          
      - run:
          name: Run vulnerability scan
          command: |
            echo "Running GemGuard security scan..."
            gem_guard scan --format json --output security-report.json
            gem_guard scan --format table
            
      - run:
          name: Generate SBOM
          command: |
            echo "Generating Software Bill of Materials..."
            gem_guard sbom --format spdx --output sbom-spdx.json
            gem_guard sbom --format cyclone-dx --output sbom-cyclone.json
            
      - store_artifacts:
          path: security-report.json
          destination: security-reports/
          
      - store_artifacts:
          path: sbom-spdx.json
          destination: sbom/
          
      - store_artifacts:
          path: sbom-cyclone.json
          destination: sbom/
          
      - run:
          name: Check for vulnerabilities
          command: |
            if [ -f security-report.json ]; then
              VULN_COUNT=$(ruby -rjson -e "puts JSON.parse(File.read('security-report.json'))['vulnerabilities']&.length || 0")
              echo "Found $VULN_COUNT vulnerabilities"
              
              if [ "$VULN_COUNT" -gt 0 ]; then
                echo "⚠️ Vulnerabilities detected! Check the artifacts for details."
                exit 1
              else
                echo "✅ No vulnerabilities found!"
              fi
            fi

  security-scan-matrix:
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    parameters:
      ruby-version:
        type: string
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install GemGuard
          command: gem install gem_guard
      - run:
          name: Security scan for Ruby << parameters.ruby-version >>
          command: |
            gem_guard scan --format json --output security-report-<< parameters.ruby-version >>.json
            gem_guard scan
      - store_artifacts:
          path: security-report-<< parameters.ruby-version >>.json

workflows:
  security-checks:
    jobs:
      - security-scan:
          name: security-scan-main
          
  security-matrix:
    jobs:
      - security-scan-matrix:
          matrix:
            parameters:
              ruby-version: ["3.1", "3.2", "3.3"]
          name: security-scan-ruby-<< matrix.ruby-version >>
    triggers:
      - schedule:
          cron: "0 2 * * *"  # Daily at 2 AM UTC
          filters:
            branches:
              only:
                - main
