name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run tests
      run: |
        bundle exec rspec --format documentation --backtrace; status=$?
        echo "RSpec exit status: $status"
        if [ "$status" -ne 0 ]; then
          echo "Diagnostics:"
          ruby -v
          bundler -v || true
          ls -lah
          git status --porcelain || true
        fi
        exit $status
    
    # SimpleCov/coverage upload removed from CI by request
    
    - name: Run linter
      run: bundle exec rake standard
      if: matrix.ruby-version == '3.3'
    
    - name: Test gem build
      run: gem build gem_guard.gemspec
      if: matrix.ruby-version == '3.3'
