name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec rspec
    
    - name: Upload to Codecov
      if: always() && matrix.ruby-version == '3.3'
      uses: codecov/codecov-action@v4
      continue-on-error: true
      with:
        use_oidc: true
        flags: ruby-${{ matrix.ruby-version }}
        fail_ci_if_error: false

    - name: Upload coverage
      if: always() && matrix.ruby-version == '3.3'
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
    
    - name: Run linter
      run: bundle exec rake standard
      if: matrix.ruby-version == '3.3'
    
    - name: Test gem build
      run: gem build gem_guard.gemspec
      if: matrix.ruby-version == '3.3'
